import 'package:coronavirus_stats_app/domain/models/country_model.dart';
import 'package:coronavirus_stats_app/domain/models/lat_long.dart';
import 'package:coronavirus_stats_app/domain/models/stats_model.dart';
import 'package:coronavirus_stats_app/domain/usecases/get_countries_usecase.dart';

class GetCountriesUseCaseStubImpl implements GetCountriesUseCase {
  Future<List<CountryModel>> getCountries({bool allowCachedData = true}) {
    return Future.delayed(Duration(seconds: 10), () {
      return [
        CountryModel(
          name: "USA",
          code: "USA",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/us.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 500000,
            todayCases: 10000,
            active: 20000,
            todayActive: 40,
            deaths: 5000,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 200,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "Germany",
          code: "DE",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/de.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 20,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "France",
          code: "FR",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/fr.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 0,
            critical: 20,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "Spain",
          code: "ES",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/es.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 20000000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 0,
            recovered: 300,
            todayRecovered: 200,
            critical: 20,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "UK",
          code: "UK",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/uk.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 0,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 20,
            todayCritical: -200000,
          ),
        ),
        CountryModel(
          name: "Netherlands",
          code: "NE",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/ne.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 200000,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "Austria",
          code: "AU",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/au.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 200000,
            todayCritical: -2,
          ),
        ),
        CountryModel(
          name: "Mexico",
          code: "ME",
          position: LatLong(),
          flagUrl: "https://corona.lmao.ninja/assets/img/flags/me.png",
          stats: StatsModel(
            updatedTime: DateTime.now().subtract(Duration(minutes: 30)),
            cases: 3000,
            todayCases: 1000,
            active: 2000,
            todayActive: 40,
            deaths: 500,
            todayDeaths: 51,
            recovered: 300,
            todayRecovered: 200,
            critical: 200000,
            todayCritical: -2,
          ),
        ),
      ];
    });
  }
}
